### ISSUE TITLE
Version >1.6 dropped support of Python2.7

### ISSUE THREAD

**Issue by akalex** [pre-commit/identify#172]
Version 1.6.x no longer supports Python2.7, the module `identify.identify.py:31` uses syntax from [PEP 448 - Additional Unpacking Generalizations](https://www.python.org/dev/peps/pep-0448) that requires Python 3.5+. 
Is it expected change or it has to be considered as a regression?

Proof:
```
$ python -V      
Python 2.7.16

$ pre-commit run -a
Traceback (most recent call last):
  File "/usr/local/bin/pre-commit", line 6, in <module>
    from pre_commit.main import main
  File "/usr/local/lib/python2.7/site-packages/pre_commit/main.py", line 11, in <module>
    from pre_commit import git
  File "/usr/local/lib/python2.7/site-packages/pre_commit/git.py", line 7, in <module>
    from pre_commit.util import cmd_output
  File "/usr/local/lib/python2.7/site-packages/pre_commit/util.py", line 15, in <module>
    from pre_commit import parse_shebang
  File "/usr/local/lib/python2.7/site-packages/pre_commit/parse_shebang.py", line 6, in <module>
    from identify.identify import parse_shebang_from_file
  File "/usr/local/lib/python2.7/site-packages/identify/identify.py", line 31
    ALL_TAGS = {*TYPE_TAGS, *MODE_TAGS, *ENCODING_TAGS}
                ^
SyntaxError: invalid syntax
```

**Comment by gabrielf-eb** [comment]
Fix
https://github.com/pre-commit/identify/pull/171

**Comment by ashanbrown** [comment]
At minimum, the major version of identify might need to be bumped.  I see this error even when I install pre-commit==1.21.0.  pre-commit has this dependency (which would still be problematic with a major version bump): https://github.com/pre-commit/pre-commit/blob/0047fa35dd463aabe85fbd55bbd97ee03479f34c/setup.cfg#L27
